config/routes.rb
Benwmiller::Application.routes.draw do
  get "home/index"

  resources :pokemons

  root :to => 'home#index'

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
  attr_accessible :color, :energy, :health, :name, :poketype
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
# Greg Miller - Canoe Creek Software - 12/29/2012
# benwmiller.com 
#
class HomeController < ApplicationController
  require './lib/pokedex'
  #include Pokedex

  def index
    a = Pokedex.new
    b = a.test_pokedex
    puts b
    puts 'yo'
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pokemons }
    end
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
    @pokemon = Pokemon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pokemon }
    end
  end

  # GET /pokemons/new
  # GET /pokemons/new.json
  def new
    @pokemon = Pokemon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pokemon }
    end
  end

  # GET /pokemons/1/edit
  def edit
    @pokemon = Pokemon.find(params[:id])
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(params[:pokemon])

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render json: @pokemon, status: :created, location: @pokemon }
      else
        format.html { render action: "new" }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pokemons/1
  # PUT /pokemons/1.json
  def update
    @pokemon = Pokemon.find(params[:id])

    respond_to do |format|
      if @pokemon.update_attributes(params[:pokemon])
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon = Pokemon.find(params[:id])
    @pokemon.destroy

    respond_to do |format|
      format.html { redirect_to pokemons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/index.html.erb
<h1 style="color: white;">Hello, Ben!</h1>
<!--<div>
  <a href="http://pokemondb.net/sprites/zekrom">
    <img src="http://img.pokemondb.net/sprites/black-white/anim/normal/zekrom.gif">
  </a>
  <a href="http://pokemondb.net/sprites/kyurem">
    <img src="http://img.pokemondb.net/sprites/black-white/anim/normal/kyurem.gif">
  </a>
  <a href="http://pokemondb.net/sprites/kyurem">
    <img src="http://img.pokemondb.net/sprites/black-white/normal/kyurem.png">
  </a>
</div>-->
<div style="color: white;">
  <%= link_to "Pokemons", pokemons_path %>
</div>  

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :health %><br />
    <%= f.text_field :health %>
  </div>
  <div class="field">
    <%= f.label :energy %><br />
    <%= f.text_field :energy %>
  </div>
  <div class="field">
    <%= f.label :poketype %><br />
    <%= f.text_field :poketype %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<h1>Listing pokemons</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Health</th>
    <th>Energy</th>
    <th>Type</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pokemons.each do |pokemon| %>
  <tr>
    <td><%= pokemon.name %></td>
    <td><%= pokemon.health %></td>
    <td><%= pokemon.energy %></td>
    <td><%= pokemon.poketype %></td>
    <td><%= pokemon.color %></td>
    <td><%= link_to 'Show', pokemon %></td>
    <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
    <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p>
  <b>Name:</b>
  <%= @pokemon.name %>
</p>

<p>
  <b>Health:</b>
  <%= @pokemon.health %>
</p>

<p>
  <b>Energy:</b>
  <%= @pokemon.energy %>
</p>

<p>
  <b>Type:</b>
  <%= @pokemon.poketype %>
</p>

<p>
  <b>Color:</b>
  <%= @pokemon.color %>
</p>


<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>